# Generated by Django 4.1.4 on 2022-12-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_record_descrip_record_usedfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='usedFor',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
