# Generated by Django 4.1.4 on 2022-12-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_record_usedfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='usedFor',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
